using System.Collections.Generic;
using System.Text;
using Godot;
using LadyBugEnemyTraceLab.TraceLab.Model;

namespace LadyBugEnemyTraceLab.TraceLab.Io;

/// <summary>
/// Writes v14 MAME-side diagnostic templates.
///
/// These files are intentionally templates, not a replacement for the Godot trace lab.
/// The goal is to make the next MAME run capture the Z80 path at the exact routines
/// that decide enemy movement: preferred load, local door rejection, fallback,
/// forced reversal, move and commit.
/// </summary>
public static class MameLuaTraceScriptWriter
{
    public const string DefaultDirectory = "res://data/mame";
    public const string LuaPath = DefaultDirectory + "/ladybug_enemy_v14_trace.lua";
    public const string DebuggerCommandsPath = DefaultDirectory + "/ladybug_enemy_v14_debugger_commands.txt";
    public const string NotesPath = DefaultDirectory + "/ladybug_enemy_v14_trace_points.md";

    public static IReadOnlyList<string> WriteDefaultFiles(IReadOnlyList<ArcadeTraceFrame> frames)
    {
        EnsureDirectory(DefaultDirectory);

        WriteText(LuaPath, BuildLuaTemplate(frames));
        WriteText(DebuggerCommandsPath, BuildDebuggerCommandTemplate());
        WriteText(NotesPath, BuildNotes(frames));

        return new[]
        {
            "Fichiers v14 écrits:",
            "  " + LuaPath,
            "  " + DebuggerCommandsPath,
            "  " + NotesPath,
            "Note: le fichier debugger_commands est volontairement un template de breakpoints MAME. Selon ta version de MAME, il faudra peut-être ajuster la syntaxe printf/action."
        };
    }

    private static void EnsureDirectory(string godotDirectory)
    {
        string absolute = ProjectSettings.GlobalizePath(godotDirectory);
        Error err = DirAccess.MakeDirRecursiveAbsolute(absolute);
        if (err != Error.Ok && err != Error.AlreadyExists)
            throw new System.InvalidOperationException($"Impossible de créer le dossier {godotDirectory}: {err}");
    }

    private static void WriteText(string godotPath, string text)
    {
        using FileAccess file = FileAccess.Open(godotPath, FileAccess.ModeFlags.Write)
                                ?? throw new System.InvalidOperationException($"Impossible d'écrire: {godotPath}");
        file.StoreString(text);
    }

    private static string BuildLuaTemplate(IReadOnlyList<ArcadeTraceFrame> frames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Lady Bug enemy movement v14 MAME Lua trace template");
        sb.AppendLine("-- Generated by LadyBug Enemy Trace Lab.");
        sb.AppendLine("-- Purpose: capture frame_done RAM state and provide a place to add breakpoint-driven logs.");
        sb.AppendLine("-- This file is deliberately conservative: frame_done logging should work with the standard MAME Lua API;");
        sb.AppendLine("-- debugger breakpoint actions may still be easier to run from ladybug_enemy_v14_debugger_commands.txt.");
        sb.AppendLine();
        sb.AppendLine("local machine = manager.machine");
        sb.AppendLine("local cpu = machine.devices[':maincpu'] or machine.devices['maincpu']");
        sb.AppendLine("assert(cpu, 'maincpu not found; check the device tag in your MAME build')");
        sb.AppendLine("local mem = cpu.spaces['program']");
        sb.AppendLine("assert(mem, 'program address space not found')");
        sb.AppendLine();
        sb.AppendLine("local out = io.open('ladybug_enemy_v14_frame_done.jsonl', 'w')");
        sb.AppendLine("assert(out, 'cannot open output file')");
        sb.AppendLine("local sample = 0");
        sb.AppendLine();
        sb.AppendLine("local function b(addr) return mem:read_u8(addr) end");
        sb.AppendLine("local function hx(v) return string.format('%02X', v & 0xff) end");
        sb.AppendLine("local function h4(v) return string.format('%04X', v & 0xffff) end");
        sb.AppendLine();
        sb.AppendLine("local trace_points = {");
        foreach (TracePoint p in TracePoints())
            sb.AppendLine($"  {{ addr = 0x{p.Address:X4}, name = '{p.Name}', why = '{p.ShortWhy}' }},");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("local function enemy(slot)");
        sb.AppendLine("  local base = 0x602b + slot * 5");
        sb.AppendLine("  local raw = b(base)");
        sb.AppendLine("  return string.format('{\"slot\":%d,\"raw\":\"%s\",\"dir\":\"%s\",\"x\":\"%s\",\"y\":\"%s\",\"sprite\":\"%s\",\"attr\":\"%s\"}',");
        sb.AppendLine("    slot, hx(raw), hx((raw >> 4) & 0x0f), hx(b(base + 1)), hx(b(base + 2)), hx(b(base + 3)), hx(b(base + 4)))");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("local function write_frame_done()");
        sb.AppendLine("  local line = string.format('{\"schema\":\"ladybug.enemyTrace.v14.frameDone\",\"sample\":%d,\"pc\":\"%s\",\"r\":\"%s\",' ..");
        sb.AppendLine("    '\"player\":{\"x\":\"%s\",\"y\":\"%s\",\"dir\":\"%s\"},' ..");
        sb.AppendLine("    '\"enemies\":[%s,%s,%s,%s],' ..");
        sb.AppendLine("    '\"enemyWork\":{\"tempDir\":\"%s\",\"tempX\":\"%s\",\"tempY\":\"%s\",\"rejectedMask\":\"%s\",\"fallbackMask\":\"%s\",' ..");
        sb.AppendLine("    '\"preferred\":[\"%s\",\"%s\",\"%s\",\"%s\"],\"chaseTimers\":[\"%s\",\"%s\",\"%s\",\"%s\"],\"rr\":\"%s\"},' ..");
        sb.AppendLine("    '\"timers\":{\"61B4\":\"%s\",\"61B5\":\"%s\",\"61B6\":\"%s\",\"61B7\":\"%s\",\"61B8\":\"%s\",\"61B9\":\"%s\",\"61E1\":\"%s\"}}',");
        sb.AppendLine("    sample, '0000', '00',");
        sb.AppendLine("    hx(b(0x6027)), hx(b(0x6028)), hx(b(0x6198)),");
        sb.AppendLine("    enemy(0), enemy(1), enemy(2), enemy(3),");
        sb.AppendLine("    hx(b(0x61bd)), hx(b(0x61be)), hx(b(0x61bf)), hx(b(0x61c1)), hx(b(0x61c2)),");
        sb.AppendLine("    hx(b(0x61c4)), hx(b(0x61c5)), hx(b(0x61c6)), hx(b(0x61c7)),");
        sb.AppendLine("    hx(b(0x61ce)), hx(b(0x61cf)), hx(b(0x61d0)), hx(b(0x61d1)), hx(b(0x61d2)),");
        sb.AppendLine("    hx(b(0x61b4)), hx(b(0x61b5)), hx(b(0x61b6)), hx(b(0x61b7)), hx(b(0x61b8)), hx(b(0x61b9)), hx(b(0x61e1)))");
        sb.AppendLine("  out:write(line .. '\\n')");
        sb.AppendLine("  sample = sample + 1");
        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("emu.register_frame_done(write_frame_done)");
        sb.AppendLine();
        sb.AppendLine("print('Lady Bug v14 frame_done trace active. Output: ladybug_enemy_v14_frame_done.jsonl')");
        sb.AppendLine("print('Trace points to add as breakpoints:')");
        sb.AppendLine("for _, p in ipairs(trace_points) do print(string.format('  %04X %s - %s', p.addr, p.name, p.why)) end");
        sb.AppendLine();
        sb.AppendLine($"-- Trace loaded in Godot when this was generated: {frames.Count} samples.");
        return sb.ToString();
    }

    private static string BuildDebuggerCommandTemplate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Lady Bug enemy movement v14 MAME debugger command template");
        sb.AppendLine("# Load idea: paste selected bpset commands in the MAME debugger, or adapt to your local Lua/debugger setup.");
        sb.AppendLine("# The action bodies are intentionally simple. If your MAME build rejects printf expressions, keep only the bpset addresses first.");
        sb.AppendLine("# Useful RAM: 61BD=tempDir, 61BE=tempX, 61BF=tempY, 61C1=rejected, 61C2=fallback, 61C4..61C7=preferred, 61CE..61D1=chase timers.");
        sb.AppendLine();
        foreach (TracePoint p in TracePoints())
        {
            sb.AppendLine($"# {p.Name}: {p.LongWhy}");
            sb.AppendLine($"bpset {p.Address:X4}");
        }
        sb.AppendLine();
        sb.AppendLine("# More verbose examples to adapt manually:");
        sb.AppendLine("# bpset 42BA,1,{printf \"EONE_ENTER PC=%04X HL=%04X E0=%02X:%02X,%02X TMP=%02X:%02X,%02X PREF=%02X,%02X,%02X,%02X CH=%02X,%02X,%02X,%02X\\n\",pc,hl,b@602b,b@602c,b@602d,b@61bd,b@61be,b@61bf,b@61c4,b@61c5,b@61c6,b@61c7,b@61ce,b@61cf,b@61d0,b@61d1;g}");
        sb.AppendLine("# bpset 4347,1,{printf \"REVERSAL_HIT PC=%04X TMP=%02X:%02X,%02X A=%02X HL=%04X PREF=%02X,%02X,%02X,%02X CH=%02X,%02X,%02X,%02X\\n\",pc,b@61bd,b@61be,b@61bf,a,hl,b@61c4,b@61c5,b@61c6,b@61c7,b@61ce,b@61cf,b@61d0,b@61d1;g}");
        sb.AppendLine("# bpset 43CE,1,{printf \"COMMIT PC=%04X TMP=%02X:%02X,%02X E0=%02X:%02X,%02X REJ=%02X FB=%02X\\n\",pc,b@61bd,b@61be,b@61bf,b@602b,b@602c,b@602d,b@61c1,b@61c2;g}");
        return sb.ToString();
    }

    private static string BuildNotes(IReadOnlyList<ArcadeTraceFrame> frames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Lady Bug enemy movement v14 trace points");
        sb.AppendLine();
        sb.AppendLine("This v14 overlay does not add a new oracle candidate. It prepares the next MAME capture so the Godot simulator can learn *which Z80 branch* produced each enemy decision.");
        sb.AppendLine();
        sb.AppendLine($"Trace loaded when generated: {frames.Count} samples.");
        sb.AppendLine();
        sb.AppendLine("## Trace points");
        sb.AppendLine();
        foreach (TracePoint p in TracePoints())
            sb.AppendLine($"- `0x{p.Address:X4}` **{p.Name}** — {p.LongWhy}");
        sb.AppendLine();
        sb.AppendLine("## Desired future JSONL event fields");
        sb.AppendLine();
        sb.AppendLine("```json");
        sb.AppendLine("{\"schema\":\"ladybug.enemyTrace.v14.z80Event\",\"sample\":123,\"event\":\"preferred_loaded\",\"pc\":\"430F\",\"slot\":0,\"tempDir\":\"04\",\"tempX\":\"68\",\"tempY\":\"96\",\"preferred\":[\"04\",\"02\",\"01\",\"08\"],\"rejectedMask\":\"00\",\"fallbackMask\":\"01\"}");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## Why this matters");
        sb.AppendLine();
        sb.AppendLine("The v13 timing probe can replay enemy0 with an enriched key, but that is still an oracle. The next step is to know whether each decision came from preferred acceptance, local door rejection, fallback, forced reversal, or commit timing.");
        return sb.ToString();
    }

    private static IEnumerable<TracePoint> TracePoints()
    {
        yield return new TracePoint(0x42BA, "enemy_update_one_enter", "entrée update", "Start of Enemy_UpdateOne for one active slot; capture HL/slot and the source slot bytes before temp copy.");
        yield return new TracePoint(0x42E6, "try_preferred_enter", "preferred path", "Entered center-decision path that will try preferred direction.");
        yield return new TracePoint(0x430F, "preferred_loaded", "dir temp", "Preferred direction has been loaded into 61BD/EnemyTemp_Dir.");
        yield return new TracePoint(0x4325, "local_door_check", "door validation", "Local door/tile validation is about to run for the tentative direction.");
        yield return new TracePoint(0x4334, "fallback_enter", "fallback", "Preferred/current direction was rejected and fallback selection is about to run.");
        yield return new TracePoint(0x4342, "forced_reversal_test", "reversal test", "Non-center forced-reversal probe via 0x4189.");
        yield return new TracePoint(0x4347, "forced_reversal_hit", "reversal hit", "Direction is actually reversed here.");
        yield return new TracePoint(0x4224, "move_one_pixel", "move", "One-pixel movement is about to be applied to the temp position.");
        yield return new TracePoint(0x43CE, "commit_temp_state", "commit", "Final temp state is committed back to the enemy slot.");
    }

    private readonly record struct TracePoint(int Address, string Name, string ShortWhy, string LongWhy);
}
